-- Specialties for clinics and categories for shops, shown at registration (spec: know the business type up front).
-- 'other' + a free-text name is available for both.
ALTER TABLE medical.specialties ADD COLUMN popular BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN sort_order INT NOT NULL DEFAULT 1000;
ALTER TABLE medical.doctors ADD COLUMN other_specialty VARCHAR(100);
CREATE TABLE commerce.store_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(40) NOT NULL UNIQUE, name_ar VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL,
    popular BOOLEAN NOT NULL DEFAULT FALSE, sort_order INT NOT NULL DEFAULT 1000, is_active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE commerce.store_category_links (
    tenant_id UUID NOT NULL REFERENCES core.tenants(id),
    category_id UUID NOT NULL REFERENCES commerce.store_categories(id),
    PRIMARY KEY (tenant_id, category_id)
);
ALTER TABLE commerce.store_profiles ADD COLUMN other_category VARCHAR(100);

INSERT INTO medical.specialties (code, name_ar, name_en, popular, sort_order) VALUES
 ('general_practice','طب عام','General practice',TRUE,1),
 ('family_medicine','طب الأسرة','Family medicine',TRUE,2),
 ('internal_medicine','الباطنة','Internal medicine',TRUE,3),
 ('pediatrics','طب الأطفال','Pediatrics',TRUE,4),
 ('obgyn','النساء والتوليد','Obstetrics & gynecology',TRUE,5),
 ('dentistry','طب الأسنان','Dentistry',TRUE,6),
 ('dermatology','الجلدية والتناسلية','Dermatology & venereology',TRUE,7),
 ('orthopedics','جراحة العظام','Orthopedics',TRUE,8),
 ('ent','الأنف والأذن والحنجرة','ENT',TRUE,9),
 ('ophthalmology','طب وجراحة العيون','Ophthalmology',TRUE,10),
 ('cardiology','القلب والأوعية الدموية','Cardiology',TRUE,11),
 ('neurology','المخ والأعصاب','Neurology',TRUE,12),
 ('psychiatry','الطب النفسي','Psychiatry',TRUE,13),
 ('urology','المسالك البولية','Urology',TRUE,14),
 ('endocrinology','الغدد الصماء والسكر','Endocrinology & diabetes',TRUE,15),
 ('gastroenterology','الجهاز الهضمي والكبد','Gastroenterology & hepatology',TRUE,16),
 ('chest','الأمراض الصدرية','Chest diseases',TRUE,17),
 ('general_surgery','الجراحة العامة','General surgery',TRUE,18),
 ('nutrition','التغذية العلاجية','Clinical nutrition',TRUE,19),
 ('physiotherapy','العلاج الطبيعي','Physiotherapy',TRUE,20),
 ('nephrology','أمراض الكلى','Nephrology',FALSE,100),
 ('rheumatology','الروماتيزم والمناعة','Rheumatology',FALSE,101),
 ('hematology','أمراض الدم','Hematology',FALSE,102),
 ('medical_oncology','علاج الأورام','Medical oncology',FALSE,103),
 ('infectious_diseases','الأمراض المعدية والحميات','Infectious diseases',FALSE,104),
 ('allergy_immunology','الحساسية والمناعة','Allergy & immunology',FALSE,105),
 ('geriatrics','طب المسنين','Geriatrics',FALSE,106),
 ('critical_care','الرعاية المركزة','Critical care',FALSE,107),
 ('emergency','طب الطوارئ','Emergency medicine',FALSE,108),
 ('sleep_medicine','طب النوم','Sleep medicine',FALSE,109),
 ('pediatric_cardiology','قلب الأطفال','Pediatric cardiology',FALSE,110),
 ('pediatric_neurology','مخ وأعصاب الأطفال','Pediatric neurology',FALSE,111),
 ('pediatric_surgery','جراحة الأطفال','Pediatric surgery',FALSE,112),
 ('pediatric_endocrinology','غدد وسكر الأطفال','Pediatric endocrinology',FALSE,113),
 ('neonatology','حديثي الولادة والحضّانات','Neonatology',FALSE,114),
 ('neurosurgery','جراحة المخ والأعصاب','Neurosurgery',FALSE,115),
 ('spine_surgery','جراحة العمود الفقري','Spine surgery',FALSE,116),
 ('cardiothoracic_surgery','جراحة القلب والصدر','Cardiothoracic surgery',FALSE,117),
 ('vascular_surgery','جراحة الأوعية الدموية والدوالي','Vascular surgery',FALSE,118),
 ('plastic_surgery','جراحة التجميل والحروق','Plastic & burn surgery',FALSE,119),
 ('surgical_oncology','جراحة الأورام','Surgical oncology',FALSE,120),
 ('bariatric_surgery','جراحة السمنة والمناظير','Bariatric & laparoscopic surgery',FALSE,121),
 ('hepatobiliary_surgery','جراحة الكبد والقنوات المرارية','Hepatobiliary surgery',FALSE,122),
 ('colorectal_surgery','جراحة القولون والمستقيم','Colorectal surgery',FALSE,123),
 ('ivf_infertility','الحقن المجهري وتأخر الإنجاب','IVF & infertility',FALSE,124),
 ('maternal_fetal','طب الجنين والحمل عالي الخطورة','Maternal-fetal medicine',FALSE,125),
 ('retina','شبكية وجسم زجاجي','Retina',FALSE,126),
 ('refractive_surgery','تصحيح الإبصار والليزك','Refractive surgery',FALSE,127),
 ('pediatric_ophthalmology','عيون الأطفال والحول','Pediatric ophthalmology',FALSE,128),
 ('audiology','السمع والتوازن','Audiology',FALSE,129),
 ('phoniatrics','التخاطب واللغة','Phoniatrics',FALSE,130),
 ('andrology','الذكورة والعقم','Andrology',FALSE,131),
 ('addiction_psychiatry','علاج الإدمان','Addiction psychiatry',FALSE,132),
 ('child_psychiatry','الطب النفسي للأطفال','Child psychiatry',FALSE,133),
 ('orthodontics','تقويم الأسنان','Orthodontics',FALSE,134),
 ('dental_implants','زراعة الأسنان','Dental implants',FALSE,135),
 ('endodontics','علاج الجذور','Endodontics',FALSE,136),
 ('pediatric_dentistry','أسنان الأطفال','Pediatric dentistry',FALSE,137),
 ('periodontology','أمراض اللثة','Periodontology',FALSE,138),
 ('prosthodontics','التركيبات والتجميل','Prosthodontics',FALSE,139),
 ('oral_maxillofacial','جراحة الفم والفكين','Oral & maxillofacial surgery',FALSE,140),
 ('radiology','الأشعة التشخيصية','Diagnostic radiology',FALSE,141),
 ('interventional_radiology','الأشعة التداخلية','Interventional radiology',FALSE,142),
 ('nuclear_medicine','الطب النووي','Nuclear medicine',FALSE,143),
 ('clinical_pathology','التحاليل الطبية','Clinical pathology (lab)',FALSE,144),
 ('pathology','الأنسجة والباثولوجي','Pathology',FALSE,145),
 ('anesthesia','التخدير','Anesthesia',FALSE,146),
 ('pain_management','علاج الألم','Pain management',FALSE,147),
 ('pm_rehab','الطب الطبيعي والروماتيزم والتأهيل','Physical medicine & rehabilitation',FALSE,148),
 ('sports_medicine','الطب الرياضي','Sports medicine',FALSE,149),
 ('aesthetic_medicine','الطب التجميلي والليزر','Aesthetic medicine & laser',FALSE,150),
 ('obesity_medicine','السمنة والنحافة','Obesity medicine',FALSE,151),
 ('preventive_medicine','الطب الوقائي والصحة العامة','Preventive medicine & public health',FALSE,152),
 ('occupational_medicine','الطب المهني','Occupational medicine',FALSE,153),
 ('clinical_genetics','الوراثة الطبية','Clinical genetics',FALSE,154),
 ('other','أخرى (اكتب تخصصك)','Other (type yours)',FALSE,9999)
ON CONFLICT (code) DO UPDATE SET name_ar = EXCLUDED.name_ar, name_en = EXCLUDED.name_en, popular = EXCLUDED.popular, sort_order = EXCLUDED.sort_order, is_active = TRUE;

INSERT INTO commerce.store_categories (code, name_ar, name_en, popular, sort_order) VALUES
 ('fashion_women','ملابس حريمي','Women''s fashion',TRUE,1),
 ('fashion_men','ملابس رجالي','Men''s fashion',TRUE,2),
 ('fashion_kids','ملابس أطفال','Kids'' fashion',TRUE,3),
 ('shoes_bags','أحذية وشنط','Shoes & bags',TRUE,4),
 ('mobiles','موبايلات وإكسسواراتها','Mobiles & accessories',TRUE,5),
 ('electronics','إلكترونيات وأجهزة منزلية','Electronics & home appliances',TRUE,6),
 ('supermarket','سوبر ماركت وبقالة','Supermarket & grocery',TRUE,7),
 ('cosmetics','مستحضرات تجميل وعناية شخصية','Cosmetics & personal care',TRUE,8),
 ('home_decor','أثاث وديكور ومفروشات','Furniture, decor & home textiles',TRUE,9),
 ('food','أكل جاهز ومطاعم','Restaurants & ready food',TRUE,10),
 ('sweets_bakery','حلويات ومخبوزات','Sweets & bakery',TRUE,11),
 ('gifts','هدايا وورد','Gifts & flowers',TRUE,12),
 ('accessories_jewelry','إكسسوارات ومجوهرات','Accessories & jewelry',FALSE,100),
 ('gold_silver','ذهب وفضة','Gold & silver',FALSE,101),
 ('watches_eyewear','ساعات ونظارات','Watches & eyewear',FALSE,102),
 ('computers','كمبيوتر ولاب توب وملحقاته','Computers & laptops',FALSE,103),
 ('gaming','ألعاب فيديو وجيمنج','Gaming',FALSE,104),
 ('fruits_vegetables','خضار وفاكهة','Fruits & vegetables',FALSE,105),
 ('meat_poultry_fish','لحوم ودواجن وأسماك','Meat, poultry & fish',FALSE,106),
 ('dairy_eggs','ألبان وجبن وبيض','Dairy & eggs',FALSE,107),
 ('coffee_tea_nuts','بن وشاي ومكسرات','Coffee, tea & nuts',FALSE,108),
 ('beverages','مشروبات وعصائر','Beverages & juices',FALSE,109),
 ('healthy_organic','منتجات طبيعية وعضوية وعطارة','Natural, organic & herbs',FALSE,110),
 ('supplements','مكملات غذائية ورياضية','Supplements & sports nutrition',FALSE,111),
 ('medical_supplies','مستلزمات طبية وأجهزة منزلية طبية','Medical supplies & home devices',FALSE,112),
 ('perfumes','عطور','Perfumes',FALSE,113),
 ('salon_supplies','مستلزمات صالونات وتجميل','Salon & beauty supplies',FALSE,114),
 ('kitchenware','أدوات مطبخ ومنزل','Kitchenware & housewares',FALSE,115),
 ('tools_hardware','عدد وأدوات كهربائية وسباكة','Tools, hardware & plumbing',FALSE,116),
 ('building_materials','مواد بناء وسيراميك وصحي','Building materials & tiles',FALSE,117),
 ('lighting_electrical','إضاءة ومستلزمات كهرباء','Lighting & electrical',FALSE,118),
 ('car_parts','قطع غيار سيارات','Car parts',FALSE,119),
 ('tires_oils','إطارات وزيوت وبطاريات','Tires, oils & batteries',FALSE,120),
 ('car_accessories','إكسسوارات سيارات','Car accessories',FALSE,121),
 ('motorcycles_bikes','موتوسيكلات وعجل','Motorcycles & bicycles',FALSE,122),
 ('toys','ألعاب أطفال','Toys',FALSE,123),
 ('baby_care','مستلزمات أطفال ورضع','Baby & infant care',FALSE,124),
 ('books_stationery','كتب وأدوات مكتبية وقرطاسية','Books & stationery',FALSE,125),
 ('school_supplies','مستلزمات مدرسية وجامعية','School supplies',FALSE,126),
 ('party_supplies','مستلزمات حفلات ومناسبات','Party supplies',FALSE,127),
 ('sports_gym','مستلزمات رياضة وجيم','Sports & gym',FALSE,128),
 ('camping_outdoor','رحلات وتخييم','Camping & outdoor',FALSE,129),
 ('pets','مستلزمات حيوانات أليفة','Pet supplies',FALSE,130),
 ('plants_garden','نباتات وزراعة وحدائق','Plants & garden',FALSE,131),
 ('farm_supplies','أعلاف ومستلزمات زراعية','Feed & agricultural supplies',FALSE,132),
 ('handmade','منتجات يدوية وهاند ميد','Handmade',FALSE,133),
 ('art_crafts','فنون وأشغال يدوية','Art & crafts',FALSE,134),
 ('music_instruments','آلات موسيقية','Musical instruments',FALSE,135),
 ('photography','كاميرات وتصوير','Cameras & photography',FALSE,136),
 ('printing_custom','طباعة وهدايا مخصصة','Printing & custom gifts',FALSE,137),
 ('islamic_items','مستلزمات دينية وحج وعمرة','Religious items, Hajj & Umrah',FALSE,138),
 ('fabrics_sewing','أقمشة وخياطة','Fabrics & sewing',FALSE,139),
 ('uniforms_workwear','يونيفورم وملابس عمل','Uniforms & workwear',FALSE,140),
 ('lingerie_sleepwear','ملابس داخلية ونوم','Lingerie & sleepwear',FALSE,141),
 ('modest_fashion','أزياء محجبات وإسدالات','Modest fashion',FALSE,142),
 ('bridal','فساتين زفاف وسهرة','Bridal & evening wear',FALSE,143),
 ('used_second_hand','مستعمل وأنتيكات','Second-hand & antiques',FALSE,144),
 ('wholesale','جملة وتجارة عامة','Wholesale & general trade',FALSE,145),
 ('other','أخرى (اكتب نشاطك)','Other (type yours)',FALSE,9999);
