name: elmanassa_business
description: Elmanassa Business - for clinics, doctors and shop owners and staff.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  platform_core:
    path: ../../packages/platform_core

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon_fg.png
  remove_alpha_ios: true
