#!/usr/bin/env python3
"""Builds backend/src/main/resources/db/migration/V18__taxonomy.sql from backend/src/main/resources/taxonomy/*.txt.

  python3 infra/scripts/gen-taxonomy-sql.py            # writes V18__taxonomy.sql
  python3 infra/scripts/gen-taxonomy-sql.py --check    # only validates the source files

V18 is generated ONCE. After it has been applied anywhere, never regenerate it: add new categories with a new migration (explicit ids above the current maximum).
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "backend/src/main/resources/taxonomy"
OUT = ROOT / "backend/src/main/resources/db/migration/V18__taxonomy.sql"

COLORS = [("black", "أسود", "Black", "#111111"), ("white", "أبيض", "White", "#FFFFFF"), ("gray", "رمادي", "Gray", "#8A8F98"), ("beige", "بيج", "Beige", "#D9C3A0"),
          ("brown", "بني", "Brown", "#7B4A2A"), ("red", "أحمر", "Red", "#D62828"), ("pink", "وردي", "Pink", "#F28DB2"), ("orange", "برتقالي", "Orange", "#F28C28"),
          ("yellow", "أصفر", "Yellow", "#F6C90E"), ("green", "أخضر", "Green", "#2E9E5B"), ("olive", "زيتي", "Olive", "#6B7A2A"), ("turquoise", "تركواز", "Turquoise", "#19B5B1"),
          ("blue", "أزرق", "Blue", "#1F6FDB"), ("navy", "كحلي", "Navy", "#14213D"), ("sky", "سماوي", "Sky Blue", "#7EC8F2"), ("purple", "بنفسجي", "Purple", "#7B3FBF"),
          ("gold", "ذهبي", "Gold", "#D4AF37"), ("silver", "فضي", "Silver", "#C0C0C0"), ("multi", "متعدد", "Multicolor", None)]
APPAREL = [("xs", "XS", "XS"), ("s", "S", "S"), ("m", "M", "M"), ("l", "L", "L"), ("xl", "XL", "XL"), ("xxl", "XXL", "XXL"), ("3xl", "3XL", "3XL"), ("4xl", "4XL", "4XL"), ("5xl", "5XL", "5XL"), ("free", "فري سايز", "Free Size")]
SHOE = [(f"eu{n}", str(n), str(n)) for n in range(18, 48)]
KIDS = [("m0-3", "0-3 شهور", "0-3 months"), ("m3-6", "3-6 شهور", "3-6 months"), ("m6-12", "6-12 شهر", "6-12 months"), ("m12-18", "12-18 شهر", "12-18 months"), ("m18-24", "18-24 شهر", "18-24 months")] + \
       [(f"y{n}", f"{n} سنة", f"{n} years") for n in range(2, 15)]
BED = [("single", "فردي", "Single"), ("double", "مزدوج", "Double"), ("queen", "كوين", "Queen"), ("king", "كينج", "King")]


def q(s):
    return "NULL" if s is None else "'" + s.replace("'", "''") + "'"


def parse():
    nodes, stack, slugs = [], [], set()
    for ln, raw in enumerate((SRC / "taxonomy.txt").read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        if indent % 2:
            sys.exit(f"taxonomy.txt:{ln}: indent must be a multiple of 2")
        level = indent // 2 + 1
        parts = [p.strip() for p in raw.strip().split("|")]
        if len(parts) < 3:
            sys.exit(f"taxonomy.txt:{ln}: need slug | ar | en")
        slug, ar, en = parts[:3]
        flags = ",".join(parts[3:])
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", slug) or slug in slugs:
            sys.exit(f"taxonomy.txt:{ln}: bad or duplicate slug {slug!r}")
        slugs.add(slug)
        while len(stack) >= level:
            stack.pop()
        if level > 1 and len(stack) != level - 1:
            sys.exit(f"taxonomy.txt:{ln}: indentation jumps a level")
        parent = stack[-1] if stack else None
        fl = {f.strip() for f in flags.split(",") if f.strip()}
        inherited = parent["flags"] if parent else {"a": False, "scales": "", "hidden": False}
        node = {"id": len(nodes) + 1, "slug": slug, "ar": ar, "en": en, "level": level, "parent": parent["id"] if parent else None,
                "path": (parent["path"] if parent else "/") + f"{len(nodes) + 1}/", "icon": next((f[5:] for f in fl if f.startswith("icon:")), None),
                "flags": {"a": "a" in fl or inherited["a"], "scales": next((f[2:].replace("+", ",") for f in fl if f.startswith("s:")), inherited["scales"]), "hidden": "hidden" in fl or inherited["hidden"]}}
        nodes.append(node)
        stack.append(node)
    return nodes


def business_map(nodes):
    slugs = {n["slug"] for n in nodes}
    out = []
    for ln, raw in enumerate((SRC / "business-map.txt").read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip() or raw.startswith("#"):
            continue
        code, rest = raw.split(":", 1)
        for s in [x.strip() for x in rest.split(",") if x.strip()]:
            if s not in slugs:
                sys.exit(f"business-map.txt:{ln}: unknown category {s}")
            out.append((code.strip(), s))
    return out


def main():
    nodes = parse()
    bmap = business_map(nodes)
    print(f"{len(nodes)} categories ({sum(1 for n in nodes if n['level'] == 1)} top level), {len(bmap)} shop-type links", file=sys.stderr)
    if "--check" in sys.argv:
        return
    ids = {n["slug"]: n["id"] for n in nodes}
    sql = ["-- GENERATED by infra/scripts/gen-taxonomy-sql.py from backend/src/main/resources/taxonomy/. Do not edit or regenerate once applied.",
           "-- Standard product categories (Egypt), standard filter values (colour, size), and which categories suit each shop type.", ""]
    sql.append("""CREATE TABLE commerce.taxonomy (
    id INT PRIMARY KEY,
    parent_id INT REFERENCES commerce.taxonomy(id),
    level SMALLINT NOT NULL,
    slug VARCHAR(80) NOT NULL UNIQUE,
    name_ar VARCHAR(120) NOT NULL,
    name_en VARCHAR(120) NOT NULL,
    path TEXT NOT NULL,
    icon VARCHAR(16),
    size_scales VARCHAR(40) NOT NULL DEFAULT '',
    applies_audience BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    search_text TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_taxonomy_path ON commerce.taxonomy (path text_pattern_ops);
CREATE INDEX idx_taxonomy_parent ON commerce.taxonomy (parent_id, sort_order);
CREATE INDEX idx_taxonomy_search ON commerce.taxonomy USING gin (search_text gin_trgm_ops);

CREATE TABLE commerce.attribute_values (
    attr VARCHAR(10) NOT NULL,            -- COLOR | SIZE
    scale VARCHAR(10) NOT NULL DEFAULT '', -- SIZE only: APPAREL | SHOE | KIDS | BED
    code VARCHAR(30) NOT NULL,
    name_ar VARCHAR(60) NOT NULL,
    name_en VARCHAR(60) NOT NULL,
    hex VARCHAR(9),
    sort_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (attr, scale, code)
);

CREATE TABLE commerce.business_type_taxonomy (
    business_code VARCHAR(40) NOT NULL,
    taxonomy_id INT NOT NULL REFERENCES commerce.taxonomy(id),
    PRIMARY KEY (business_code, taxonomy_id)
);

CREATE TABLE commerce.taxonomy_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES core.tenants(id),
    name VARCHAR(120) NOT NULL,
    parent_id INT REFERENCES commerce.taxonomy(id),
    note VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(10) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    admin_note VARCHAR(500) NOT NULL DEFAULT '',
    taxonomy_id INT REFERENCES commerce.taxonomy(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at TIMESTAMPTZ
);
CREATE INDEX idx_taxonomy_requests_status ON commerce.taxonomy_requests (status, created_at);

ALTER TABLE commerce.products
    ADD COLUMN taxonomy_id INT REFERENCES commerce.taxonomy(id),
    ADD COLUMN audience VARCHAR(10) NOT NULL DEFAULT '',          -- MEN | WOMEN | BOYS | GIRLS | BABY | ALL (or empty when it does not apply)
    ADD COLUMN item_condition VARCHAR(12) NOT NULL DEFAULT 'NEW'; -- NEW | USED | REFURBISHED
CREATE INDEX idx_products_taxonomy ON commerce.products (tenant_id, taxonomy_id);

ALTER TABLE commerce.product_options
    ADD COLUMN attribute_code VARCHAR(10) NOT NULL DEFAULT '',   -- COLOR | SIZE for standard options, empty for custom ones
    ADD COLUMN size_scale VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE commerce.product_option_values ADD COLUMN value_code VARCHAR(30) NOT NULL DEFAULT '';
""")
    rows = []
    for i, n in enumerate(nodes):
        rows.append(f"({n['id']}, {n['parent'] if n['parent'] else 'NULL'}, {n['level']}, {q(n['slug'])}, {q(n['ar'])}, {q(n['en'])}, {q(n['path'])}, {q(n['icon'])}, {q(n['flags']['scales'])}, {'TRUE' if n['flags']['a'] else 'FALSE'}, {i}, {'TRUE' if n['flags']['hidden'] else 'FALSE'})")
    sql.append("INSERT INTO commerce.taxonomy (id, parent_id, level, slug, name_ar, name_en, path, icon, size_scales, applies_audience, sort_order, is_hidden) VALUES\n" + ",\n".join(rows) + ";")
    sql.append("UPDATE commerce.taxonomy SET search_text = commerce.norm_ar(name_ar || ' ' || name_en);\n")
    vals = []
    for i, (c, ar, en, hx) in enumerate(COLORS):
        vals.append(f"('COLOR', '', {q(c)}, {q(ar)}, {q(en)}, {q(hx)}, {i})")
    for scale, lst in (("APPAREL", APPAREL), ("SHOE", SHOE), ("KIDS", KIDS), ("BED", BED)):
        for i, (c, ar, en) in enumerate(lst):
            vals.append(f"('SIZE', '{scale}', {q(c)}, {q(ar)}, {q(en)}, NULL, {i})")
    sql.append("INSERT INTO commerce.attribute_values (attr, scale, code, name_ar, name_en, hex, sort_order) VALUES\n" + ",\n".join(vals) + ";\n")
    sql.append("INSERT INTO commerce.business_type_taxonomy (business_code, taxonomy_id) VALUES\n" + ",\n".join(f"({q(c)}, {ids[s]})" for c, s in bmap) + ";")
    OUT.write_text("\n".join(sql) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}", file=sys.stderr)


main()
